Network structure
EdgeLab-FHDO/Edge-Diagnostic-Platform pull request #79
Opened 2021-01-16 17:53 UTC by lkh5kor

- Added folder network structure as part of [InfrastructureManager](https://github.com/EdgeLab-FHDO/Edge-Diagnostic-Platform/tree/master/src/main/java/InfrastructureManager) with the required classes and few functions.

The first two commits contains basic class definitions. Range check for latitude, longitude and distance calculation from latitude and longitude which would be useful later. 

Pending items:
1. Relation classes implementation.
2. JSON string read and write implementation.
3. Addition of comments to all files.

Creating pull request so as to start the review and also to discuss further steps.

2021-01-18 20:01 UTC, alyhasansakr commented
@lkh5kor Is it ready for review? you requested my review but I still see a lot of TODO's in the code.

2021-01-18 20:24 UTC, lkh5kor commented
> @lkh5kor Is it ready for review? you requested my review but I still see a lot of TODO's in the code.

@alyhasansakr , The complete implementation is not done. As per our previous discussion, I have created the pull request. Few of the todo are related to the additional functions like distance calculation using latitude, longitude co ordinates, range checks for latitude and longitude values... etc. which we decided to keep it as it is and later move them to different files/classes.
JSON string read and write and relationship between classes are pending.

2021-01-18 20:27 UTC, alyhasansakr commented
@lkh5kor Creating a pull-request is not the same as requesting a review. You should only request a review when you are done with the implementation and the code is ready to be reviewed.

2021-01-23 20:39 UTC, lkh5kor commented
@alyhasansakr ,
As per our discussion, I have updated the changes, unit testing is also done. 
Documentation/Comments are also added.
The pull request is now ready for review.
Kindly review 

Regards,
Shankar

2021-01-24 10:25 UTC, alyhasansakr requested changes
some of the comments are written only once but apply for more than one case, always check similar cases in your code.

2021-01-24 10:25 UTC, alyhasansakr commented on src/main/java/InfrastructureManager/NetworkStructure/Network.java
> +		//New object created as the called object cannot be accessed as a whole. Therefore new object is created to update the calling object members with values from json string
it is better to write a copy function here.

2021-01-24 10:25 UTC, alyhasansakr commented on src/main/java/InfrastructureManager/NetworkStructure/Network.java
> +		} catch (Exception ex) {
why are you both handling and throwing exceptions at the same time?
here you shouldn't handle exceptions.

2021-01-24 10:25 UTC, alyhasansakr commented on src/main/java/InfrastructureManager/NetworkStructure/Network.java
> +    public List<Device> getDeviceList() {
I would advice against a full access to the device list, instead, a function that gets a device by its id makes more sense (mutable or not)

2021-01-24 10:25 UTC, alyhasansakr commented on src/main/java/InfrastructureManager/NetworkStructure/Network.java
> +    public  void setDeviceList(List<Device> deviceList) {
setting the whole list is not recommended, instead, adding and removing a specific device should be implemented.

2021-01-24 10:25 UTC, alyhasansakr commented on src/test/java/InfrastructureManager/NetworkStructure/NetworkTest.java
> +		System.out.println(writeString);
no need to print anything while testing, this is automatically done when a test fails.

2021-01-24 10:25 UTC, alyhasansakr commented on src/test/java/InfrastructureManager/NetworkStructure/NetworkTest.java
> +	    Assert.assertEquals(1, deviceID0);
you only tested the first device id value, what about all of the others values that you assigned?
and what about writeString?
also, you are mixing between testing the setters and testing saveNetwork, each should has its own test.

2021-01-24 10:25 UTC, alyhasansakr commented on src/test/java/InfrastructureManager/NetworkStructure/NetworkTest.java
> +    	//Network network = mapper.readValue(jSON, Network.class);
don't leave commented code without a reason.

2021-01-24 10:25 UTC, alyhasansakr commented on src/test/java/InfrastructureManager/NetworkStructure/NetworkTest.java
> +	    Assert.assertEquals(2, deviceID1);
and what about everything else you included in the json string?

2021-01-24 10:55 UTC, lkh5kor commented on src/main/java/InfrastructureManager/NetworkStructure/ComputeLimits.java
> +	public void setCpuCount(int cpuCount) {
Wouldn't the setters be required at a later stage when you allocate cpu, gpu and memory for application and when you free them up after the application is completed.?

2021-01-24 11:01 UTC, lkh5kor commented on src/main/java/InfrastructureManager/NetworkStructure/Connection.java
> +	public void setNetworkCapacity(NetworkLimits networkCapacity) {
Wouldn't the setters be required at a later stage when a new connection is established or existing connection is disconnected.? For requirements we may not need the setters as it is fixed but here don't we need the setters?

2021-01-24 11:36 UTC, lkh5kor commented on src/main/java/InfrastructureManager/NetworkStructure/NetworkLimits.java
> +	public void setLatency(int latency) {
Wouldn't the setters be required at a later stage when a new connection is established or existing connection is disconnected.?

2021-01-24 11:51 UTC, alyhasansakr commented on src/main/java/InfrastructureManager/NetworkStructure/NetworkLimits.java
> +	public void setLatency(int latency) {
that would be a part of a different implementation, and it will not use a setter in this way.

2021-01-24 11:53 UTC, alyhasansakr commented on src/main/java/InfrastructureManager/NetworkStructure/ComputeLimits.java
> +	public void setCpuCount(int cpuCount) {
part of future implementation.

2021-01-24 11:53 UTC, alyhasansakr commented on src/main/java/InfrastructureManager/NetworkStructure/Connection.java
> +	public void setNetworkCapacity(NetworkLimits networkCapacity) {
part of future implementation.

2021-01-24 23:21 UTC, lkh5kor commented
@alyhasansakr ,
The review findings are fixed.
Read from JSON String test case(loadNetworkTest) is commented as the string length is exceeding the max size required for Jackson serialization, otherwise all the other test cases are covered and assertion checks have passed.

2021-01-24 23:24 UTC, lkh5kor commented
@alyhasansakr ,
The review findings are fixed.
Read from JSON String test case(loadNetworkTest) is commented as the string length is exceeding the max size required for Jackson serialization, otherwise all the other test cases are covered and assertion checks have passed.
Sorry, the PR was closed by mistake, I have reopened it.

2021-01-25 23:26 UTC, alyhasansakr commented
@lkh5kor that is really good, there are still a few things that we are going to improve along the way.
Now you need to merge the master branch into this branch and write a new class NetworkModule that extends PlatformModule. The new module should have an output that creates a new network and an input that gives the current network.

2021-01-26 09:16 UTC, juan-castrillon commented
@lkh5kor Documentation is still needed for the modules, however to start follow this:

# How to create a new module

1. In the folder `src/main/java/InfrastructureManager/Modules` create a new folder with the module's name
2. Inside the new package create the module class (extending `PlatformModule`) and a `RawData` package with the raw representation of the module (`extends ModuleConfigData`).
3. In `src/main/java/InfrastructureManager/ModuleManagement/RawData/ModuleConfigData.java` add the new raw data class as a json subtype
4. In `src/main/java/InfrastructureManager/ModuleManagement/ModuleFactory.java` add a new type to the `ModuleType` enum
5. In the raw representation add the new type as the type parameter
6. Again in the factory handle the new case in the switch expression to return a new Module

2021-01-26 18:56 UTC, lkh5kor commented
@alyhasansakr, @juan-castrillon,
I have made the requested changes as per my understanding. Kindly review.
I am not aware of the current exception handling of modules. I have modified the src\main\java\InfrastructureManager\ModuleManagement\ModuleInput.java to handle one of the JSON exceptions as it was giving me error. I think that's not the proper way to handle the exception. 
Kindly let me know how it is to be handled.

2021-01-26 19:15 UTC, alyhasansakr commented on src/main/java/InfrastructureManager/Modules/NetworkStructure/Input/NetworkInput.java
> +    public String read() throws JsonProcessingException  {
here only InterruptedException could be throw. JsonProcessingException or any other exception must be handled in this function.

2021-01-26 19:15 UTC, alyhasansakr commented on src/main/java/InfrastructureManager/ModuleManagement/ModuleInput.java
> +    public abstract String read() throws InterruptedException, JsonProcessingException;
remove JsonProcessingException

2021-01-26 19:15 UTC, alyhasansakr commented on src/main/java/InfrastructureManager/ModuleManagement/ModuleOutput.java
> +import com.fasterxml.jackson.core.JsonProcessingException;
remove JsonProcessingException

2021-01-26 19:34 UTC, alyhasansakr approved these changes

2021-01-26 19:36 UTC, merged